
// NETWORK NAME AND PASSWD

#define SECRET_SSID <SSID HERE>
#define SECRET_PWD <PASSWD HERE>

// BROKER USER / PASSWD

#define BROKER_USER <BROKER NAME HERE>
#define BROKER_PWD <BROKER PWD HERE>

// DEVICE ID -- change for every unit
#define DEVICE <DEVICE NAME HERE>
